from src.callbacks.training_callbacks.training_filters import register_training_filter_callbacks
from src.callbacks.training_callbacks.training_summary_cards import register_training_summary_cards_callbacks
from src.callbacks.training_callbacks.training_engaged_members import register_training_engaged_members_callbacks
from src.callbacks.training_callbacks.training_engaged_members import register_training_chart_modal_callbacks
from src.callbacks.training_callbacks.training_office_engagement import register_training_office_engagement_callbacks
from src.callbacks.training_callbacks.training_office_engagement import register_training_office_engagement_modal_callbacks
from src.callbacks.training_callbacks.training_session_scheduling import register_training_session_scheduling_callbacks
from src.callbacks.training_callbacks.training_session_scheduling import register_training_session_scheduling_modal_callbacks
from src.callbacks.training_callbacks.training_instructor_performance import register_training_instructor_performance_callbacks
from src.callbacks.training_callbacks.training_instructor_performance import register_training_instructor_performance_modal_callbacks
from src.callbacks.training_callbacks.training_gap_analysis import register_training_gap_analysis_callbacks
from src.callbacks.training_callbacks.training_gap_analysis import register_training_gap_analysis_modal_callbacks
from src.callbacks.training_callbacks.training_data_table import register_training_data_table_callbacks

from src.callbacks.workflow_callbacks.workflow_filters import register_workflow_filter_callbacks
from src.callbacks.workflow_callbacks.workflow_summary_cards import register_workflow_summary_cards_callbacks
from src.callbacks.workflow_callbacks.workflow_ticket_volume import register_workflow_ticket_volume_callbacks
from src.callbacks.workflow_callbacks.workflow_ticket_volume import register_workflow_ticket_volume_modal_callbacks
from src.callbacks.workflow_callbacks.workflow_status_distribution import register_workflow_status_distribution_callbacks
from src.callbacks.workflow_callbacks.workflow_status_distribution import register_workflow_status_distribution_modal_callbacks
from src.callbacks.workflow_callbacks.workflow_resolution_times import register_workflow_resolution_times_callbacks
from src.callbacks.workflow_callbacks.workflow_resolution_times import register_workflow_resolution_times_modal_callbacks
from src.callbacks.workflow_callbacks.workflow_classification_analysis import register_workflow_classification_analysis_callbacks
from src.callbacks.workflow_callbacks.workflow_classification_analysis import register_workflow_classification_analysis_modal_callbacks
from src.callbacks.workflow_callbacks.workflow_assignee_workload import register_workflow_assignee_workload_callbacks
from src.callbacks.workflow_callbacks.workflow_escalated_tickets import register_workflow_escalated_tickets_callbacks
from src.callbacks.workflow_callbacks.workflow_source_analysis import register_workflow_source_analysis_callbacks
from src.callbacks.workflow_callbacks.workflow_product_impact import register_workflow_product_impact_callbacks
from src.callbacks.workflow_callbacks.workflow_user_performance import register_workflow_user_performance_callbacks
from src.callbacks.workflow_callbacks.workflow_trends_analysis import register_workflow_trends_case_reasons_issues_callbacks
from src.callbacks.workflow_callbacks.workflow_data_table import register_workflow_data_table_callbacks

from src.callbacks.compliance_callbacks.compliance_filters import register_compliance_filter_callbacks
from src.callbacks.compliance_callbacks.compliance_summary_cards import register_compliance_summary_cards_callbacks
from src.callbacks.compliance_callbacks.compliance_violation_status import register_compliance_violation_status_callbacks
from src.callbacks.compliance_callbacks.compliance_outstanding_issues import register_compliance_outstanding_issues_callbacks
from src.callbacks.compliance_callbacks.compliance_recent_activities import register_compliance_recent_activities_callbacks
from src.callbacks.compliance_callbacks.compliance_agent_performance import register_compliance_agent_performance_callbacks
from src.callbacks.compliance_callbacks.compliance_violation_trends import register_compliance_violation_trends_callbacks
from src.callbacks.compliance_callbacks.compliance_incident_analysis import register_compliance_incident_analysis_callbacks

def register_all_callbacks(app):
    register_training_filter_callbacks(app)
    register_training_summary_cards_callbacks(app)
    register_training_engaged_members_callbacks(app)
    register_training_chart_modal_callbacks(app)
    register_training_office_engagement_callbacks(app)
    register_training_office_engagement_modal_callbacks(app)
    register_training_session_scheduling_callbacks(app)
    register_training_session_scheduling_modal_callbacks(app)
    register_training_instructor_performance_callbacks(app)
    register_training_instructor_performance_modal_callbacks(app)
    register_training_gap_analysis_callbacks(app)
    register_training_gap_analysis_modal_callbacks(app)
    register_training_data_table_callbacks(app)

    register_workflow_filter_callbacks(app)
    register_workflow_summary_cards_callbacks(app)
    register_workflow_ticket_volume_callbacks(app)
    register_workflow_ticket_volume_modal_callbacks(app)
    register_workflow_status_distribution_callbacks(app)
    register_workflow_status_distribution_modal_callbacks(app)
    register_workflow_resolution_times_callbacks(app)
    register_workflow_resolution_times_modal_callbacks(app)
    register_workflow_classification_analysis_callbacks(app)
    register_workflow_classification_analysis_modal_callbacks(app)
    register_workflow_assignee_workload_callbacks(app)
    register_workflow_escalated_tickets_callbacks(app)
    register_workflow_source_analysis_callbacks(app)
    register_workflow_product_impact_callbacks(app)
    register_workflow_user_performance_callbacks(app)
    register_workflow_trends_case_reasons_issues_callbacks(app)
    register_workflow_data_table_callbacks(app)

    register_compliance_filter_callbacks(app)
    register_compliance_summary_cards_callbacks(app)
    register_compliance_violation_status_callbacks(app)
    register_compliance_outstanding_issues_callbacks(app)
    register_compliance_recent_activities_callbacks(app)
    register_compliance_agent_performance_callbacks(app)
    register_compliance_violation_trends_callbacks(app)
    register_compliance_incident_analysis_callbacks(app)
